# fly.toml app configuration file generated for ordem-da-fenix-api
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ordem-da-fenix-api"
primary_region = "gru"  # São Paulo, Brasil

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.env]]
  PYTHON_VERSION = "3.12"